import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import {
  LinkArrow,
  NextJS,
  NextLogo,
  NextjsLogo,
  PrismaLogo,
  ReactIcon,
  TailwindIcon,
  TypescriptIcon,
  TypescriptLogo,
  VercelLogo,
} from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";
import { motion } from "framer-motion";
import {
  TwitterIcon,
  GithubIcon,
  LinkedInIcon,
  PinterestIcon,
  DribbbleIcon,
  SunIcon,
  MoonIcon,
} from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hiro Nakae | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />

      <main className="flex items-center min-h-screen ">
        <Layout className="pt-0 md:pt-16 sm:pt-8 ">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              {/* <Image
                src={profilePic}
                alt="HiroNakae"
                className="w-full h-auto md:inline-block md:w-full "
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              /> */}
            </div>
            <div className="w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Hiro Nakae"
                className="my-4  !text-left lg:!text-center 2xl:!text-6xl xl:!text-5xl lg:!text-4xl md:!text-3xl"
              />
              <AnimatedText
                text="Hi there. I'm a Software Engineer based in Eugene, Oregon."
                className="!text-lg font-semibold md:!text-sm sm:!text-xs  !text-start lg:!text-center"
              />
              {/* <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Get highly-performing, fully functional and secure web
                experiences that are able to scale as your business grows.
              </p> */}

              <nav className="flex items-center justify-start flex-wrap my-4 lg:!justify-center">
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 mr-4"
                  title="Next.js"
                >
                  <NextJS />
                </motion.div>
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 mx-4"
                  title="React.js"
                >
                  <ReactIcon />
                </motion.div>
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 mx-4"
                  title="Typescript"
                >
                  <TypescriptIcon />
                </motion.div>
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 mx-4"
                  title="Tailwind CSS"
                >
                  <TailwindIcon />
                </motion.div>
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 mx-4"
                  title="Vercel"
                >
                  <VercelLogo />
                </motion.div>
                <motion.div
                  whileHover={{ y: -2 }}
                  whileTap={{ scale: 0.9 }}
                  className="w-6 ml-4"
                  title="Prisma ORM"
                >
                  <PrismaLogo />
                </motion.div>
              </nav>

              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="h-[50px] w-[150px] flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2 dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                {/* <Link
                  href="/contact"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  HIRE ME
                </Link> */}
              </div>
            </div>
          </div>
        </Layout>
      </main>
      {/* <HireMe text="Hire me!" /> */}

      {/* <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={penguin} alt="HiroNakae" className="w-full h-auto" />
        </div> */}
    </>
  );
}
